version: '3.8'
services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass password --save 60 1
    networks:
      - notes-network

  postgres_note_service:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes-db
    ports:
      - "60001:5432"
    volumes:
      - postgres-note-service-data:/var/lib/postgresql/data
    networks:
      - notes-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - notes-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - notes-network

  clickhouse:
    image: clickhouse/clickhouse-server:25.5
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - notes-network

  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - notes-network

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    networks:
      - notes-network
  
  liquibase_notes_service:
    image: liquibase/liquibase:4.27.0
    volumes: 
      - ./note-service/migrations:/liquibase/changelog
    command: >
      sh -c "sleep 5 && liquibase
      --url=jdbc:postgresql://postgres_note_service:5432/notes-db
      --username=user
      --password=password
      --driver=org.postgresql.Driver
      --classpath=/liquibase/changelog/postgresql-42.7.3.jar
      --changeLogFile=changelog/db/db.changelog-master.xml
      update"
    depends_on:
      - postgres_note_service
    networks:
      - notes-network

  postgres_auth_service:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth-db
    ports:
      - "60002:5432"
    volumes:
      - postgres-auth-service-data:/var/lib/postgresql/data
    networks:
      - notes-network

  liquibase_auth_service:
    image: liquibase/liquibase:4.27.0
    volumes: 
      - ./auth-service/migrations:/liquibase/changelog
    command: >
      sh -c "sleep 5 && liquibase
      --url=jdbc:postgresql://postgres_auth_service:5432/auth-db
      --username=user
      --password=password
      --driver=org.postgresql.Driver
      --classpath=/liquibase/changelog/postgresql-42.7.3.jar
      --changeLogFile=changelog/db/db.changelog-master.xml
      update"
    depends_on:
      - postgres_auth_service
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge

volumes:
  redis-data:
  postgres-note-service-data:
  postgres-auth-service-data:
  clickhouse-data:
